spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.138.60.227:3306/vip_service_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: viptester
    password: Abcd!1234
  redis:
    host: 10.138.60.227
    port: 6399
    password: viphuiyuan
    database: 0
server:
  port: 9890
debug: true
