spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
  datasource:
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
  mail:
    host: smtp.263.net
    username: vipsystemcenter@vcredit.com
    password: vipcenter2018!!
    default-encoding: UTF-8
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  typeAliasesPackage: com.vc.domain
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: null

pagehelper:
  helper-dialect: mysql
  reasonable: true
